# Generated by Django 2.0b1 on 2017-11-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetwo',
            name='text',
            field=models.TextField(max_length=720, verbose_name='Стихотворение'),
        ),
    ]
